### ISSUE TITLE
Some config questions

### ISSUE THREAD

**Issue by mufasa85** [georged/code-connectors#2]
Hi, i was just wondering what i'm supposed to input on the **"Host"** and **"Base URL"** field when setting this up as a custom connector, and also which authentication method is recommended? This will be used as part of Amey Holdens' flow for importing a marketing list to Dynamics 365, so the users will be azure ad users.

**Comment by georged** [comment]
It really does not matter because the request never makes it to the "host". 

We use
 
  "host": "api.contoso.com",
  "basePath": "/",

If you create connector by importing [CSV-To-Json.swagger.json](https://github.com/georged/csvtojson/blob/main/CSV-To-Json.swagger.json) these values will be used.

**Comment by mufasa85** [comment]
ah i see, thank you George. 

Which auth method did you use for this?

**Comment by georged** [comment]
None as we don't have a service to secure.

**Comment by mufasa85** [comment]
ah ok, i'll give it a try then, just asked because i got warnings from PA when trying to set it up. Thank you for the quick response.
